export const experienceData = [
  {
    id: 1,
    position: "Next.js全栈工程师",
    company: "Work for Myself",
    location: "Remote",
    website: "",
    duration: "2024.7 - Present",
    logo: "",
    description:
      "在这段时间中，参与了很多项目的开发。比如Soca、FameEx等项目。还参与了多个项目的维护工作。",
    technologies: [
      "Next.js",
      "Tailwind",
      "React testing library",
      "TypeScript",
      "Express",
      "Nest.js",
      "PostgreSQL",
    ],
  },
  {
    id: 2,
    position: "Node.js全栈工程师",
    company: "法本信息",
    location: "上海",
    website: "https://www.farben.com.cn/",
    duration: "2023.5 - 2024.5",
    logo: "",
    description:
      "在法本信息，我参与了项目管理平台的开发。一个基于React.js和Express开发的管理平台。我参与了该项目中大部分的前端开发和部分后端开发。如需求管理、项目管理、产品管理、采购管理等页面。以及权限管理、用户管理、角色管理等接口设计和实现。",
    technologies: [
      "React.js",
      "Tailwind",
      "TypeScript",
      "Zustand",
      "Node.js",
      "PostgreSQL",
      "Docker",
    ],
  },
  {
    id: 3,
    position: "高级前端开发工程师",
    company: "博彦科技",
    location: "杭州",
    website: "",
    duration: "2019.8 - 2023.4",
    logo: "",
    description:
      "参与了多个项目的开发，包括基于React和Java的信用贷平台以及相关的管理后台。在这两个项目中，我主要负责前端开发，包括移动端适配、功能实现、性能优化等。与产品经理紧密合作，优化转化漏斗并实施A/B测试框架，以推动增长计划。",
    technologies: ["React", "JavaScript", "Redux", "Node.js"],
  },
  {
    id: 4,
    position: "前端开发工程师",
    company: "赤兔网络科技",
    location: "南京",
    website: "",
    duration: "2018.5 - 2019.7",
    logo: "",
    description: "负责开发酒店官网以及酒店管理后台。",
    technologies: ["React", "Node.js", "Express", "MySQL"],
  },
];
